data:
    name: tartanair
    data_dir: TartanAir
    info_file: TartanAir.pickle
    batch_size: 128
    num_workers: 14
    fmin: 1
    fmax: 100
    load_features:
        do: false  # enable this if you have cached predictions
model:
    name: two_view_pipeline
    extractor:
        name: gluefactory_nonfree.superpoint
        max_num_keypoints: 512
        force_num_keypoints: True
        detection_threshold: 0.0
        nms_radius: 3
        trainable: False
    ground_truth:
        name: matchers.depth_matcher
        th_positive: 3
        th_negative: 5
        th_epi: 5
        min_depth: 1e-4
    matcher:
        name: matchers.simpleglue
        weights: superpoint_lightglue  # This will initalize from ligthglue weights
        filter_threshold: 0.1
        logvar_filter_threshold: 1
        flash: false
        checkpointed: false false
train:
    seed: 0
    optimizer: adamw
    epochs: 50
    start_epoch_tr_logvar: 0
    log_every_iter: 100
    eval_every_iter: 500
    lr: 1e-4
    clip_grad: 10
    lr_schedule:
        start: 20
        type: OneCycleLR
        options:
            epochs: 50
            steps_per_epoch: 500
            max_lr: 1e-4
            pct_start: 0.1
            anneal_strategy: linear
            cycle_momentum: False
            div_factor: 10
            final_div_factor: 10000
        on_epoch: false
        exp_div_10: 10
    dataset_callback_fn: sample_new_items
    plot: [5, 'gluefactory.visualization.visualize_batch.make_match_figures']
